---
title: "Teaching"
---

**Independent Instructor:**

* Technopolitics: AI and Political Systems [Summer 2025](Walker_429_Syllabus_S25.pdf){target="_blank"}

* American Government and Politics: [Spring 2025](Walker_101_Syllabus_S25.pdf){target="_blank"}

* Global Green Politics: [Summer 2022,](Walker_327_Syllabus_S22.pdf){target="_blank"} [Summer 2023](Walker_327_Syllabus_S23.pdf){target="_blank"}, [Winter 2024](Walker_327_Syllabus_W24.pdf){target="_blank"}

**Workshops:**

* Introduction to Mathematics for Political Science Graduate Students: [2022](Math_Workshop_22.pdf){target="_blank"}, [2023](walker_mathworkshop_24.pdf){target="_blank"}, [2024](walker_mathworkshop_24.pdf){target="_blank"}, [2025](Math_Workshop_25.pdf){target="_blank"}

**Teaching Assistant:**
*Introduction to Political Analysis: 2024

* MLE, Machine Learning, and Regime Change (Graduate): 2024

* Introduction to Political Analysis: 2024

* Introduction to Environmental Policy: 2023

* International Relations Among Rich and Poor Nations: 2022

* Global Green Politics: 2021

**Teaching Certificates:**
* IMPACT-X Course Redesign (2025)

* Teaching Through Online Forums/Discussions Mini Course (2023)

* IMPACT-X Course Redesign (2022)

* Certificate of Foundations in College Teaching (2021)

<!-- ## Course Evaluations -->

<!-- ### Student Evaluation Scores -->
<!-- *Values presented as Mean (Median) on a 5-point scale* -->

<!-- | Question | Global Green Politics Summer 22 | Global Green Politics Summer 23 | Global Green Politics Winter 24 | American Government Spring 25 | Technopolitics: AI & Political Systems Summer 25 | -->
<!-- |----------|--------------------------------|--------------------------------|--------------------------------|------------------------------|------------------------------------------------| -->
<!-- | The course is well organized. | 4.86 (5) | 4.73 (5) | 3.94 (5) | 4.48 (4) | 4.83 (5) | -->
<!-- | The assignments aid me in achieving the class objectives. | 4.71 (5) | 4.73 (5) | 3.94 (4) | 4.43 (5) | 4.67 (5) | -->
<!-- | The projects aid me in achieving the class objectives. | 4.86 (5) | 4.60 (5) | 3.94 (4) | 4.26 (5) | 4.50 (5) | -->
<!-- | The instructor communicates clearly. | 4.86 (5) | 4.67 (5) | 4.25 (5) | 4.57 (5) | 4.67 (5) | -->
<!-- | The instructor effectively answers students' questions. | 5.00 (5) | 4.67 (5) | 4.50 (5) | 4.43 (5) | 4.50 (5) | -->
<!-- | The instructor seems to care about my learning in this course. | 4.86 (5) | 4.60 (5) | 4.25 (5) | 4.35 (5) | 4.50 (5) | -->
<!-- | The instructor makes time to help students. | 4.86 (5) | 4.60 (5) | 4.19 (4) | 4.39 (5) | 4.50 (5) | -->
<!-- | The instructor is fair in evaluating my performance in the course. | 4.86 (5) | 4.60 (5) | 4.13 (4) | 4.52 (5) | 4.67 (5) | -->
<!-- | The instructor created an inclusive learning environment. | 4.86 (5) | 4.67 (5) | 4.25 (4.5) | 4.57 (5) | 4.67 (5) | -->
<!-- | My instructor shows respect for diverse groups of people. | 4.83 (5) | 4.71 (5) | 4.71 (5) | 4.71 (5) | 4.80 (5) | -->

### Student Feedback

**Transparency**

* "Everything was very well organized, easy to follow, and instructions were given very clearly"

* "I appreciate how quickly Prof. Walker responded to my question earlier in the semester. I hope Professor Walker continues to be as transparent as she has been throughout the session."

* "Engaging activities and clear expectations on assignments."

* "The instructor communicated clearly. I enjoyed listening to the instructor because the directions were clear."

* "She genuinely cares about student participation and success in all of her classes and she does an exemplary job at explaining the concepts in a way that aids students."

* "Excellent organization, relevant and helpful assignments, good variety of materials, responsive communication, passionate about the course topics, very quick grading, and good feedback. Probably the best online class I've taken."

* "Professor Walker was always available if you had any questions or if you were confused about something, which was so useful since this was an online summer course."

* "Professor Walker is very good at keeping students updated on what is due and when each week. If a question is asked, she responds as fast as possible."

* "I also appreciate how you gave as much feedback as you could on our assignments to help keep me on track."

* "I also valued her responsiveness to questions and feedback, as it made it clear that she genuinely cared about our understanding and success."

* "The professor is very understanding and compassionate with some things I was going through."

* "Professor Walker does a great job of answering questions when they are asked in class."

* "Makes time for the students despite having a busy schedule and is very kind and accommodating."

**Interactive Learning Environment**

* "The course material reinforced things I already knew, but also challenged some pre-existing ideas I had and gave me the opportunity to learn more and adjust based on what we read and saw."

* "I feel like the mix of readings, videos, lectures, and assignments were extremely beneficial in giving me a full understanding of the concepts. I usually don't feel like online classes are very profitable or that I've learned very much, but I honestly think this was very productive and I've definitely learned a lot."

* "Uploading assignments on Perusall is also helpful because I can see what my classmates are thinking about the assignments instead of just being in an online bubble by myself."

* "Activities in class kept people engaged."

* "I think the use of Perusall was a great collaborative platform for students in the class. It was very beneficial in instances when certain passages of text were confusing or foreign due to specific political vocabulary, which gave students the opportunity to explain further in depth."

* "One thing Christina Walker does exceptionally well is creating a welcoming and supportive learning environment. Her ability to explain complex concepts in a clear and accessible way is something I really appreciated and hope she continues to do in the future. Additionally, the inclusion of diverse learning materials, such as videos and interactive discussions, made the class engaging and kept the content relevant."

**Authentic Assessments**

* "One of the most clearly organized courses with assignments that all felt relevant and aided me in my learning. She wasn't too demanding, just focusing on us learning the main points. I wish every teacher was like her."

* "Overall, I really enjoyed this course and I think I learned a lot that I can apply to everyday life. I liked learning about the background of climate change and how some propaganda came out of it. I thought that was very interesting and am glad it was covered in this course."

* "I've enjoyed the assignments and have been able to apply the knowledge of our course to them and have had the opportunity to expand my knowledge by also making connections to material outside of the course with our course content."

* "The instructor did incredibly well in explaining topics with activities to aid in the learning process."

* "She makes sure to provide information and also explain why it is relevant to our daily lives."

* "I hope she continues fostering this open communication and providing real-world applications of the material, as it truly enriches the learning experience."


