name: automatically update CV PDF from Overleaf

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight
  workflow_dispatch:

jobs:
  get-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Sbrjt/overleaf-resume-syncer@main
        with:
          overleaf_url: 'https://www.overleaf.com/read/pcczthmkhfjn#bcbc65'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Move PDF to cv folder
        run: mv resume.pdf cv/cv.pdf

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add cv/cv.pdf
          git diff --staged --quiet || git commit -m "Update CV PDF"
          git push
